name: ecommerce_app
description: A simple e-commerce app built with Flutter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 # For API requests
  provider: ^6.0.5 # State management
  flutter_secure_storage: ^8.0.0 # Secure storage
  cupertino_icons: ^1.0.6 # iOS Icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
``
